### ISSUE TITLE
Pregenerating world console error

### ISSUE THREAD

**Issue by Enchilada246** [Zathrox/Explorercraft#10]
I've used the worldborder pluguin to pregenerate a modded world using aternos and this error appears. 
ExplorerCraft loaded a new chunk [-62, -155] in dimension 0 (overworld) while populating chunk [-62, -156], causing cascading worldgen lag.
It asks me to report it to the mod's issue tracker, idk if this's the place to report it. Also, it says that this log can be disbled in the forge config. How can I enter there? Thanks!

**Comment by Zathrox** [comment]
Hey, there sorry for the reply, this is a common error in forge and it is usually caused when something generates outside the chuck it is in and causes another chunk to load, this is normal with large structures and its happens uncommonly I believe with my Ash Trees, as they are huuuge! it's a perfectly normal error to see unless, you see it spammed and constantly but as a one off every now and again, its good!

As for how to disable it, I do not actually know how, as its a forge thing and I've not discovered how myself!
