### ISSUE TITLE
Game freezes on 100% during new world load

### ISSUE THREAD

**Issue by dreckz** [Zathrox/Explorercraft#14]
Minecraft: 1.15.2
Forge: 31.1.27
Explorercraft: 4.0.0

Supposed to happen:  World the game world on the new world.

What actually happens: New game world does not load.

[latest.log](https://github.com/Zathrox/Explorercraft/files/4391564/latest.log)

**Comment by Zathrox** [comment]
Hello, I believe my mod isn't compatible with the better respawn mod, I had another player come to me with the issue, my sleeping bag sets spawn/sleeps the player and I think better respawn changes how that works and is conflicting

try removing better respawn mod and test if that loads the world

I've also messaged Better respawn mod about how we could go about fixing the issue for the long term
