### ISSUE TITLE
Explorercraft 1.15.2 does not register any features/structures to Forge's registery

### ISSUE THREAD

**Issue by TelepathicGrunt** [Zathrox/Explorercraft#15]
Hello! I was testing Explorercraft with my mod, World Blender, which takes other mod's features and structures and shoves it all into one chaotic dimension. However, I noticed that while my mod can import Explorercraft's awesome features directly from the biomes, the features/structures does not have resourcelocations and the structures cannot be found using the /locate command. This means that the features and structures in Explorercraft aren't registered to Forge's Feature registry.

If you do register them to the registry, it wont change the functionality of your mod but it'll let it be more compatible with other mods (some mods might need the features registered so they can import them from the registry. My mod needs features registered so user can blacklist specific features from other mods). Good luck and your mod is looking real awesome so far!

**Comment by Zathrox** [comment]
Unfortunately, i've not been able to get the magic combination to get my "structures" registered as structures like mineshafts/igloos, i've tried a few times as i'd love to use the locate command and stuff that comes with it but alas, i've failed to get it working, if you know how to do it, help would be appreciated.

*edit* I do use the old way of registering as it works and I haven't converted over to the new system, so maybe that could be the issue too

**Comment by Zathrox** [comment]
I didn't do a direct pull and merge as after you creating this intial issue, I decided to go have another bash at making it work and I managed to get something working as you posted this pull request and I manually merged it with what work I had done already but thank you for it, the comments were incredibly helpful in my understanding of the structures and I now have the wizard tower as a structure that generates as such and can use the locate comment, etc, it also helped solved some issues I had with spawning in entities in the structure!

So the new update coming out soon should fix your issues, please let me know if they don't. The dungeon isn't a structure yet, will work on that at a later date but it should be a registered feature atleast!
