### ISSUE TITLE
[1.15.2]Request to add string

### ISSUE THREAD

**Issue by EnterFor** [Zathrox/Explorercraft#18]
![image](https://user-images.githubusercontent.com/10114685/78043823-6b4a0580-73a6-11ea-9c9c-ab551d471b03.png)
![image](https://user-images.githubusercontent.com/10114685/78043865-76049a80-73a6-11ea-8f61-adb07bceab93.png)
It's a very nice Mod. I love it.
I will continue to test

**Comment by EnterFor** [comment]
2. I want the fireball from the wand not to destroy the block

**Comment by Zathrox** [comment]
Fixed the two translation issues mentioned above, if you want the fireball from the staff, set mobgriefing to false, that will disable the explosion
