### ISSUE TITLE
[1.15.2] [Crash on New World Load] Ticking Memory Error

### ISSUE THREAD

**Issue by dreckz** [Zathrox/Explorercraft#19]
MC: 1.15.2
Forge: 31.1.30
Explorercraft: 4.0.0

Upon attempting to load a new world, it freezes at 100% and a crash long is created:
Crash Log:
[crash-2020-04-01_13.50.02-server.txt](https://github.com/Zathrox/Explorercraft/files/4417089/crash-2020-04-01_13.50.02-server.txt)
https://paste.gg/p/anonymous/bb8f1cff76644bfba09f65392b8fe550

Found error in latest log too:
https://paste.gg/p/anonymous/3b68ae03f0de452298b1140c3fcc4d33

**Comment by Zathrox** [comment]
Unfortunately, my mod isn't compatible with the Better Respawn mod, whatever it is they do to the game for the respawning conflicts with my sleeping bag mechanics, I have approached the owners of the mod to ask how we possibly go about fixing this issue but until further notice, you'll have to choose between one of our mods
