### ISSUE TITLE
oreDict compat [Suggestion]

### ISSUE THREAD

**Issue by MasterSloth1** [Zathrox/Explorercraft#2]
could u change your recipes for the tools and armour to use tags instead specific items please and thank you 😄 , in the zip file below is the recipes changed 😄 
[explorercraftRecipeFix.zip](https://github.com/Zathrox/Explorercraft/files/3727291/explorercraftRecipeFix.zip)

**Comment by Zathrox** [comment]
You know, that is oddly something I have been completely oblivious too! I've made all the custom tags and everything for the forge tags just never thought to change the recipes! and as to your question, I most certainly can! thanks for doing the hard work on fixing the tags too! :D

It'll come with the next update :)

**Comment by Zathrox** [comment]
#
