### ISSUE TITLE
[1.15.2]Server crash

### ISSUE THREAD

**Issue by EnterFor** [Zathrox/Explorercraft#20]
unknown aetiology...
[debug.log](https://github.com/Zathrox/Explorercraft/files/4419426/debug.log)
[crash-2020-04-02_15.21.17-server.txt](https://github.com/Zathrox/Explorercraft/files/4419427/crash-2020-04-02_15.21.17-server.txt)
The client is fine

**Comment by Zathrox** [comment]
thanks for this, i've figured out the issue, the endereeper was blowing up all your servers so i've put him in time out, next release of my mod should fix the server issue
