### ISSUE TITLE
Infected mobs not obeying light level

### ISSUE THREAD

**Issue by lamoyrl90** [Zathrox/Explorercraft#21]
I keep having Brush Stooges, Creepings and Infected Skeletons spawning all over my caves even when it's lit up past light level 7. Is this intentional?

**Comment by lamoyrl90** [comment]
MC 1.15.2, Explorercraft 4.0.1 btw

**Comment by Zathrox** [comment]
Thanks for reporting this! this isn't intended, I think I know where this issue might be stemming from (a lot of mob registration was changed in my 1.15 version to standardize it)

**Comment by Suberox** [comment]
Hi, lamoyrI90 just confirming that yes this is indeed a bug and is being looked into. Thank you for your feedback!

**Comment by Zathrox** [comment]
Resolved in 4.0.2

**Comment by Suberox** [comment]
Verified.
