### ISSUE TITLE
Amethyst, Jade, and Ruby can be mined with a Wooden Pickaxe.

### ISSUE THREAD

**Issue by FamiliarGecko** [Zathrox/Explorercraft#22]
The Amethyst, Jade, and Ruby ores can be mined with a Wooden Pickaxe.

I'm assuming that they're ment to require at least Iron tier. (Apologies if it's not the case!)

(Version: Explorercraft-1.15.2-4.0.1)

**Comment by Zathrox** [comment]
You are correct, I will look into this! thanks for reporting it!

**Comment by Zathrox** [comment]
Added in harvest level checks.
Jade/Ruby now require an harvest level 2 (iron/amethyst)
Amethyst ore requires harvest level 1 (stone)

Resolved in 4.0.2

**Comment by Suberox** [comment]
I have tested this again and I tested 4 different types of pickaxes

Wooden pickaxe 
Stone pickaxe 
Iron Pickaxe 
Amethyst pickaxe

With all 4 pickaxes, I tested each one on Jade/Ruby/Amethyst ores. with each type of pickaxe, it broke and dropped materials for all 3 ores with all 4 pickaxes.

**Comment by Zathrox** [comment]
Resolved in final version of patch 4.0.2

**Comment by Suberox** [comment]
Verified.
