### ISSUE TITLE
Lotus Flower issue

### ISSUE THREAD

**Issue by Suberox** [Zathrox/Explorercraft#23]
**User Reported Issue:**
User Potted Planter left some feedback on the ExplorerCraft Discord. "I'm not sure if it's intended to be such a way but the explorercraft water lily pads, while they look really pretty, you can't stand on them like vanilla lily pads" 

**Bug:**
Lotus flowers have a visual lily pad in them but aren't able to be walked on like vanilla water lilies, is this intended?

**Steps to reproduce:**
1. X
2. Y
3. Z

**Description:**
So I looked into this by first checking if lily pad were working fine. I placed one on a 1 block deep water surface and walked on it and jumped up and down on it no issues. 

But once I placed mud underneath it and placed a Lotus flower on top of the lily pad, as these were the ones the user was giving feedback about. Once this was placed I went to stand on the lily pad and I fell straight through it and was in the water on top of the mud block. I could come back up again but this acted like just going through water. 

I am unsure if this is an intended design feature or if this is a bug feature. 

Gareth.

**Comment by Zathrox** [comment]
This is a feature, although it has a lily pad inside it, it isn't meant to be walked on, its a decorative item.

Wont fix.
