### ISSUE TITLE
Spelling Error "Chiselled" 

### ISSUE THREAD

**Issue by Suberox** [Zathrox/Explorercraft#24]
User Radiation reported spelling errors on the word "Chiselled" here is the message. "oh yeah, also chiseled is spelled with one L, not two. so "chiselled slate" ain't the right spelling" 

I went onto the server and I went into a creative world. I typed in the word "chise". and all of the items associated with that. but the user is incorrect with the spelling I checked a dictionary and the correct spelling is "Chiselled". But this did, however, bring up other incorrect spellings on the items I made a shortlist of all of the misspelt items.

Chiseled Sandstone
Infested Chiseled Stone Bricks
Chiseled Stone Bricks
Chiseled Quartz Block
Chiseled Red Sandstone

All of these items have misspellings as stated before it's spelt Chiselled with 2 "lls". 

The other 3 items with the word chiselled are correct just to show you the 3 that are correct. 

Chiselled Basalt Bricks
Chiselled Marble Bricks 
Chiselled Slate

So here are some items that need correcting. Please let me know if I could contact the user about the issue. 

Gareth.

**Comment by Zathrox** [comment]
After checking the configs, I've created a en_GB language file to preserve the British English and then amended the en_US version to have the US spelling. 

Resolved in version 4.0.2

**Comment by Suberox** [comment]
Verified on both US and UK languages.
