### ISSUE TITLE
Endereeper spawn issue.

### ISSUE THREAD

**Issue by Suberox** [Zathrox/Explorercraft#25]
User alexandru201111 on the Twitch mod page reported a bug issue. "sadly  in 1.15.2 i can't spawn the endereeper also it don't spawn at all in the end" 

I opened up the mod in creative mode and had an Endereeper egg and tried spawning loads of endereepers all over the place I tried spawning them at different levels working perfectly fine. Also tried spawning them on top of other items like flowers and trees again working fine. I tried spawning them in different biomes again no issues found. 

I then looked into the second issue with them not spawning in the End so I again used the egg and tried spawning the Endereeper within the End and again no issues I tried spawning it at different levels and on top of other items again no issues so far. 

I shall contact the user and see if I can get some more information on this area. 

Gareth.

**Comment by Suberox** [comment]
An update on this I have tried this on both Survival and Creative mode and now and the user is correct on the creative mode it's fine but on survival trying to spawn an Endereeper doesn't work both in the end and in the normal world. 

Gareth.

**Comment by Zathrox** [comment]
Regarding this issue, did you also find any naturally spawning endereepers? as they should spawn slightly rarer than enderman in the End?

**Comment by Zathrox** [comment]
Resolved in 4.0.2

**Comment by Suberox** [comment]
Verified.
