### ISSUE TITLE
Rice Bug

### ISSUE THREAD

**Issue by Suberox** [Zathrox/Explorercraft#27]
**User Reported Issue:** 
DriftyDeath reported _"following up on what you said about the rice. So I just did a test on two different computers on two versions of forge for your mod for Minecraft 1.15.2, these versions are 31.1.25, and 31.2.4. can confirm that breaking the top rice block does not break the bottom block. But breaking the bottom block breaks the top block."_  

**Bug:** 
The rice block isn't breaking all the way down to the bottom block.

**Steps to reproduce:** 
I went into a game world and got some rice. I then spawned some into the water and it spawned the 2 rice blocks as intended I first hit the bottom block and it broke the whole item and dropped rice. I then placed more rice and then hit the top block and the bottom block was leftover. 

**Side note:**
The bottom block didn't break when the top one was hit. Also, the bottom block won't regrow any new rice I am unsure if this is intentional or not.

**Comment by Zathrox** [comment]
Resolved in version 4.0.2

**Comment by Suberox** [comment]
Verified.
