### ISSUE TITLE
ExplorerCraft Tree Bug

### ISSUE THREAD

**Issue by Suberox** [Zathrox/Explorercraft#28]
**User Reported Issue:** 
From user DriftyDeath: _"It turns out even with your mod as the only mod on the client, the trees from your mod do no grow. or they grow at such a slow rate that with a day of testing I could not get a single tree from explorer craft to grow without the use of bone meal. this is a pretty major bug as now the trees from your mod are essentially not farmable via tree farms without bone meal."_

**Bug:**
The bug seems to be that none of your mod trees is growing in the mod at all even when its the only mod on the server. They only grow when using Bonemeal. 

**Steps to reproduce:** 
I opened a world and I placed these trees in a big open grid to test each tree. The ones I tested from your mod are: 

Willow Sapling 
Sakura Sapling
Bamboo Sapling
Maple Sapling
Ash Sapling

As I stated I placed all of these in a big grid. I had 5 of each tree in rows on a big open dirt area. I then waited for 3 in-game days, nothing happened. I then also got some Spruce Saplings and planted them nearby to see if they would grow. After an in-game day, the Spruce Saplings grew. 

**Side note:**
I then tried the Bonemeal on each of the Explorer Saplings and each of them grew immediately, except for the Ash Saplings. The Ash Saplings wouldn't grow at all. Even when using Bonemeal I even tried a single ash sapling on an open area and it still wouldn't grow.

**Comment by Zathrox** [comment]
Thanks for the feedback in testing this. 

In regards to the ash tree sapling, you need 9 saplings in a grid to grow them (can you confirm this on the wiki/ingame?) as they are big trees and require more saplings to grow

**Comment by Suberox** [comment]
I shall test this later I didn't know you had to do that for those trees will test this.

**Comment by Zathrox** [comment]
Resolved in 4.0.2

**Comment by Suberox** [comment]
Verified.
