### ISSUE TITLE
Pink Glowshroom Feedback

### ISSUE THREAD

**Issue by Suberox** [Zathrox/Explorercraft#29]
**User Reported Issue:** 
User Radiation feedback: "currently, only the green glowshroom can be used to make infected willow logs, and the pink glowshroom has no use besides as decoration
perhaps a pink variant of infected willow logs could be introduced, or at least let pink glowshroom be used in the same crafting recipe, or maybe even a new one"

**Feedback:**
The user would like some more use with the Pink Glowshroom. rather than just having a use for decoration.

**Comment by Zathrox** [comment]
Added in all wood variants for pink infected wood, has recipes using willow wood and pink glowshrooms.

Added in 4.0.2

**Comment by Suberox** [comment]
Missing language files for all pink infected log blocks.

**Comment by Suberox** [comment]
The pink infected log recipe for doors, fences, buttons and gates are not automatically unlocked in the recipe book.

**Comment by Zathrox** [comment]
Resolved in latest addition of 4.0.2 patch

**Comment by Suberox** [comment]
Verified.
