### ISSUE TITLE
Ice mountain biome crashing server

### ISSUE THREAD

**Issue by zEpiixz** [Zathrox/Explorercraft#3]
I would guess the mountains are way to big and are crashing my server everytime someone visits them ^^. It doesnt give a crash log sadly.

**Comment by Zathrox** [comment]
Hello there, I don't add an ice mountain biome in my mod? so you sure its my biome that's causing an issue?

**Comment by zEpiixz** [comment]
Yes i got the advancment "snowdonia - The land of Song!" right before.

**Comment by Zathrox** [comment]
Hmm if your server is crashing due to the world generation, there isn't much I can do for that other than suggest put more dedicated ram on your server, i'm running a small server with the mod to and have no issues with world gen, obviously, if you can find an actual crash log where its breaking the server, I can look into that.

One tip I can give is simply go into the config options and reduce the forested mountain and snowdonia weights, it'll make them more rare and hopefully you'll encounter them less frequently and it wont tax your server so much?

**Comment by zEpiixz** [comment]
My deepest apologies for your concerns. After the guy who crashed everything coudnt provide enough information i checked myself and the snowdonia was just a random biome next to the crashing biome so he thought it was from that. But after i got deeper into it  was the biome from wild nature.
But thanks for your advice but i think with 10gbs ram are we good on 50 mods ^^.

**Comment by Deylendor** [comment]
I'm sorry but I am having the same issue without even having the mentioned "wild nature" mod.
It happened in 2 worlds of mine both in proximity to the Snowdonia biome, 

Maybe comparing load orders from myself and zEpiixz could shed some light.
<details><pre>
alchemistry-1.14.4-7.jar
alib-1.14.4-7.jar
AmbientSounds_v3.0.14_mc1.14.4.jar
Apotheosis-1.14.4-2.4.2.jar
AppleSkin-mc1.14.4-forge-1.0.12.jar
Aquaculture-1.14.4-2.0.2.jar
BambooBlocksV1.2.2.jar
bluepower-1.14.4-0.3.135-alpha-universal.jar
Bones-1.14.4-1.3.1.jar
buildinggadgets-3.0.6a.jar
caelus-FORGE-1.14.4-1.0.jar
CapabilityProxy-1.14.4-2.1.4.jar
CarryOn MC1.14.4 v1.12.4.jar
cc-tweaked-1.14.4-1.85.0.jar
chemlib-1.14.4-10.jar
Clumps-4.0.0.jar
ColossalChests-1.14.4-1.7.4.jar
colytra-FORGE-1.14.4-2.0.jar
compressed_items-1.14.4-1.1.jar
CosmeticArmorReworked-1.14.4-v1a.jar
create-mc1.14.4_v0.1.1a.jar
Cyclic-1.14.4-0.0.12.jar
CyclopsCore-1.14.4-1.5.5.jar
dankstorage-1.10.jar
Druidcraft-1.14-0.1.31.jar
elevatorid-1.14.4-1.5.2.jar
engineersdecor-1.14.4-1.0.15-b1.jar
EverlastingAbilities-1.14.4-1.5.5.jar
Explorercraft-1.14.4-3.2.3.jar
extcaves-1.3.2.jar
extraboats-1.1.2-1.14.4.jar
farlanders-1.14.4-1.1.0.jar
FastFurnace-1.14.4-2.2.4.jar
FastLeafDecay-v17.jar
Flopper-1.14.4-1.0.4.jar
furniture-7.0.0-pre11-1.14.4.jar
Harvest-forge-1.14.4-1.2.10-23.jar
inventorysorter-1.14.4-16.2.0.jar
ironchest-1.14.4-9.1.5.jar
ironshulkerboxes-1.14.4-3.1.12.jar
jei-1.14.4-6.0.0.18.jar
LargeFluidTank-14.8.4.jar
Mantle-1.14.4-1.4.32.jar
mcjtylib-1.14-3.5.9-alpha.jar
metalbarrels-1.3d.jar
mightyarchitect-mc1.14.4_v0.5.jar
minecolonies-0.10.472-RELEASE-universal.jar
MiniCoal2-1.14.4-0.0.1-universal.jar
Morpheus-1.14.4-4.2.43.jar
MouseTweaks-2.12-mc1.14.4.jar
mysticallib-1.14.4-1.5.jar
mysticalworld-1.14.4-1.6.1.jar
parachutemod-1.14.4-2.2.1-456.jar
Placebo-1.14.4-2.3.1.jar
planttech2-0.01.04.jar
PotionCapsule-1.1.1.jar
RandomThings-MC1.14.4-5.0.1.jar
rftoolsbase-1.14-0.0.6-alpha.jar
rftoolsbuilder-1.14-1.2.5-alpha.jar
rftoolspower-1.14-1.2.6-alpha.jar
rftoolsutility-1.14-1.2.6-alpha.jar
rsgauges-1.14.4-1.1.9-b2.jar
ScalableCatsForce-2.13.1-with-library.jar
SilentLib-1.14.4-4.4.0+44.jar
SilentMechanisms-1.14.4-0.6.7+40.jar
simpleportals-1.14.4-1.6.0.1.jar
simplylight-0.9.0.jar
solcarrot-1.14.4-1.9.3.jar
StorageDrawers-1.14.4-6.0.5.jar
structurize-0.10.194-ALPHA.jar
swingthroughgrass-1.14.4-1.3.2.jar
theoneprobe-1.14-1.4.37.jar
titanium-1.14.4-2.2.0-d9775a7.jar
TMechworks-1.14.4-2.0-beta3.jar
tombstone-4.1.6-1.14.4.jar
ToolBelt-1.14.4-1.12.5.jar
useful_backpacks-1.14.4-1.7.1.41.jar
u_team_core-1.14.4-2.7.4.134.jar
vilnames_1.14-1.4.jar
xercamusic-1.14.4-1.3.jar
XL-Food-Mod-1.14.4-2.1.1.jar

**Comment by Zathrox** [comment]
I'll need a crash-log report if you want me to seriously look at this, i've been running a server with my mod and not had any issues, it is most likely a mod conflicting somehow and there are to many mods in that list for me to reliable test, so without a log, you'll have to do that yourself
