### ISSUE TITLE
Enderghast bug

### ISSUE THREAD

**Issue by Suberox** [Zathrox/Explorercraft#30]
**User Reported Issue:** 
_"cool mod but sadly the ender ghast don't spawn at all in the end even with the latest version of 1.12.2 and in the config the spawning is set to true I tried to found him but sadly didn't found any"_

**Bug:**
Enderghast is not spawning in the end. 

**Steps to reproduce:** 
I created a world and went to the end. I wondered around the end for about 20 mins. Nothing spawned. 

**Side note:**
I also spawned some within the end and they flew straight up into the void open space in the end and disappeared.

**Comment by Zathrox** [comment]
As of the testing session yesterday, I increased the spawn rate for enderghasts in the 1.15.2 and after testing 1.12.2 version, the enderghast spawned in before the enderreeper, so I can only surmise that his collection of mods is interfering with the spawn, therefore can't fix.

**Comment by Suberox** [comment]
Verified.
