### ISSUE TITLE
New patch features

### ISSUE THREAD

**Issue by Zathrox** [Zathrox/Explorercraft#31]
Please test and review:

- A new monster has been added to the mod: Skeletaur! 
- [x] It currently spawns in the plains, flower forest and sunflower field biomes
- [x] Drops bones
- [x] Chases and attacks the player

- Noctiluca plants changes
- [x] Noctiluca plants world generation can be disabled / enabled in the config files
- [x]  Noctilucas fruits can be eaten even when full

- Wizard changes:
- [x] Fixed issues with rare items requiring multiply items (e.g Nether star trade only needs 1 item, before it was asking for X amount)

- Brush Stooge changes
- [x] Increased movement speed of the brush stooges, they should be moving fast

**Comment by Suberox** [comment]
All tested all verified.
