### ISSUE TITLE
Achievement issue.

### ISSUE THREAD

**Issue by Suberox** [Zathrox/Explorercraft#34]
**User Reported Issue:**
DinoKiller65: _"Guys, I have a problem, always when I start playing all of the achievements, well most of them are unlocked."_

**Bug:**
All achievements unlocking when the world is started up.

**Steps to reproduce:**
I created a world and explored and not all of the achievements have unlocked. Unable to reproduce.

**Side note:**
May have occurred due to other mods installed. I will enquire about this with the user.

**Comment by Zathrox** [comment]
Closing as porting to 1.16
