### ISSUE TITLE
Issue with silent gear/lib

### ISSUE THREAD

**Issue by grandogarndo** [Zathrox/Explorercraft#38]
An issue with silents mods in which tons of loot tables, in my case nether fortress chests, are just gone, and you can't even get them with /loot. silent said it would take two lines of code but who would write it I don't know. link: https://github.com/SilentChaos512/SilentGems/issues/414

**Comment by Zathrox** [comment]
Oh hey, sorry for the late reply, I read the post and I actually fixed the issue with conflicts months ago. The two line fix comment I believe was a dig at the forge team, implying that if they simply did a fix, of about 2 lines of code, then this issue wouldn't crop up and make mods even more compatible. however there is nothing more I can do! 

Maybe you could report it also to the forge team github issues channel?

**Comment by grandogarndo** [comment]
the discord was pretty unresponsive, but I will try the GitHub. that's nice to know as your mod is so great and I dint want to delete it.
