### ISSUE TITLE
[1.14] Ash saplings not growing?

### ISSUE THREAD

**Issue by sugary-stardust** [Zathrox/Explorercraft#4]
I bonemealed an Ash Sapling (while in creative for an infinite amount) and no amount seemed to make the sapling grow. Maybe it needs way more space than usual to grow?

**Comment by Zathrox** [comment]
Hello, the ash tree is similar to large jungle/dark oak trees were you need 4 saplings for it to work and I do believe based on the spawn code, you do need some extra flat space around it, so a 4x4 area of flat surface and a 2x2 of saplings, hope this helps?

I'll try and remember to add this information to the wiki so people can have help figuring it out later!
