### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Warbringer12** [Zathrox/Explorercraft#45]
keep crashing on startup

1.16.5-5.0.0

[debug.log](https://github.com/Zathrox/Explorercraft/files/6176457/debug.log)
[latest.log](https://github.com/Zathrox/Explorercraft/files/6176458/latest.log)
[crash-2021-03-20_14.39.41-fml.txt](https://github.com/Zathrox/Explorercraft/files/6176459/crash-2021-03-20_14.39.41-fml.txt)

**Comment by Zathrox** [comment]
Thanks for reporting! I've fixed the issue and triple checked that it loads, got into a world! Let me know if you discover any other issues!

New update 5.0.1 is up on curseforge!
