### ISSUE TITLE
[1.16.5] Way too much large bamboo grove biomes on terraforged w/ no config

### ISSUE THREAD

**Issue by MrKashew** [Zathrox/Explorercraft#46]
Would be nice to tune w/ config or integrate w/ terraforged
![image](https://user-images.githubusercontent.com/53996665/112401620-2eb69e80-8cc8-11eb-9554-74eba2ea31d0.png)

**Comment by Zathrox** [comment]
Thanks for the feedback, the next version of the mod addresses this, I've reimplemented the configuration system + tweaked the bamboo grove spawn weight so its much much rarer than it is this common! Should come out on the weekend!
