### ISSUE TITLE
Can't create sticks out of Maple or Cherry Blossom planks

### ISSUE THREAD

**Issue by SchrabbelTech** [Zathrox/Explorercraft#49]
In normal minecraft you can create sticks out of planks using the carft interface by putting two planks vertically. This does not work for Maple and Cherry Blossom planks.

My configuration:
Minecraft 1.6.5
Forge 1.16.5-36.1.3

My mods:
antiqueatlas-5.4.4-forge.jar
AppleSkin-mc1.16.2-forge-1.0.14.jar
betteranimalsplus-1.16.4-10.1.0.jar
BiomesOPlenty-1.16.4-13.0.0.434-universal.jar
Druidcraft-1.16.5-0.4.52.jar
explorercraft-5.0.2.jar
extcaves-2.4.jar
gravestone-1.16.5-1.0.3.jar
Hwyla-forge-1.10.11-B78_1.16.2.jar
jei-1.16.5-7.6.1.75.jar
minecolonies-0.14.70-ALPHA-universal.jar
NaturesAura-34.2.jar
Neat+1.7-27.jar
pamhc2crops-1.16.3-1.0.1.jar
pamhc2foodcore-1.16.3-1.0.2.jar
pamhc2trees-1.16.3-1.0.0.jar
Patchouli-1.16.4-48.jar
premium-wood-1.16.4-1.3.4.jar
RingOfTeleport-1.16.3-1.2.4.jar
simpleplanes-1.16.4-4.1.2.jar
StorageDrawers-1.16.3-8.2.2.jar
structurize-0.13.148-ALPHA-universal.jar
[1.16.5]+SecurityCraft+v1.8.21.1.jar

**Comment by Zathrox** [comment]
Thanks, I believe this and your other tickets are related to forge tags, I'm guessing I missed some for the logs/planks to enable these recipes! I'll try and get something out soon for them!
