### ISSUE TITLE
Asian gateway created floating above ground

### ISSUE THREAD

**Issue by SchrabbelTech** [Zathrox/Explorercraft#50]
In my game i encountered a nice asian looking agteway. However that was generated floating above the gound ...

![2021-04-01_17 23 33](https://user-images.githubusercontent.com/79862812/113317228-70ba9280-930f-11eb-8ab7-a6b073cb24bd.png)

My configuration:
Minecraft 1.6.5
Forge 1.16.5-36.1.3

My mods:
antiqueatlas-5.4.4-forge.jar
AppleSkin-mc1.16.2-forge-1.0.14.jar
betteranimalsplus-1.16.4-10.1.0.jar
BiomesOPlenty-1.16.4-13.0.0.434-universal.jar
Druidcraft-1.16.5-0.4.52.jar
explorercraft-5.0.2.jar
extcaves-2.4.jar
gravestone-1.16.5-1.0.3.jar
Hwyla-forge-1.10.11-B78_1.16.2.jar
jei-1.16.5-7.6.1.75.jar
minecolonies-0.14.70-ALPHA-universal.jar
NaturesAura-34.2.jar
Neat+1.7-27.jar
pamhc2crops-1.16.3-1.0.1.jar
pamhc2foodcore-1.16.3-1.0.2.jar
pamhc2trees-1.16.3-1.0.0.jar
Patchouli-1.16.4-48.jar
premium-wood-1.16.4-1.3.4.jar
RingOfTeleport-1.16.3-1.2.4.jar
simpleplanes-1.16.4-4.1.2.jar
StorageDrawers-1.16.3-8.2.2.jar
structurize-0.13.148-ALPHA-universal.jar
[1.16.5]+SecurityCraft+v1.8.21.1.jar

**Comment by Zathrox** [comment]
Thanks, i'll check it out, i'm wondering if its a production vs dev bug, in dev it was constantly in the ground, so I made it spawn 2 blocks above and maybe in dev it spawns properly and my changes made it float! Or its a random one off but i'll double check!

**Comment by Zathrox** [comment]
Unfortunately, i've generated several worlds both in Dev and production and all my Torii gates spawn in the ground, I'm wondering if this is a mod conflict or a rare random fluke. I'll keep an eye on it for now.

**_Edit,_** its kind of hard to see from the picture but there are random bushes that aren't part of my mod, there is a good chance that maybe those bushes are considered "replaceable" like normal grass/plants and thats what caused my structure to spawn "above" them, if this is the case, it might be worth mentioning it to that mods author about them.

**Comment by SchrabbelTech** [comment]
I'll check if there's anything below the gate (haven't changed the place so far)
Anyway i keep looking for another gateway in the game just to see if that too spawned "floating"

**Comment by SchrabbelTech** [comment]
Though i haven't encountered a second gateway so far i think you are right that the floating placement is the result of objects below the gateway itself. I went again to the structure and checked what/if there's something beneath.
One side is totally clear whereas the other side has three below the gateway:

One block of thick bamboo
![2021-04-04_19 10 30](https://user-images.githubusercontent.com/79862812/113516265-9054f380-9579-11eb-8436-982c71388282.png)

One Shaded Garden from the **Pam's Harvestcraft 2 mod**
![2021-04-04_19 10 39](https://user-images.githubusercontent.com/79862812/113516286-af538580-9579-11eb-993c-d4ada7fb0908.png)

One Grass blcok from minecraft itself:
![2021-04-04_19 10 42](https://user-images.githubusercontent.com/79862812/113516315-d3af6200-9579-11eb-926c-439e224d4b90.png)

**Comment by Zathrox** [comment]
Yeah in all my tests and worlds, this has never happened, at least not for grass blocks or my bamboo trees, so yeah under that assumption I think it was because of that shaded garden bush. Not sure what I can do from it on my end but I'll tinker as I work on porting the mod and see what I can improve! Keep me posted if you discover anything else!

**Comment by Zathrox** [comment]
Closing for now, if you find another instance of this, please feel free to post again. Thanks for playing!
