### ISSUE TITLE
Can't craft Jade Longbow

### ISSUE THREAD

**Issue by FLoCkeYE** [Zathrox/Explorercraft#51]
Hi there, I'm enjoying your mod to the fullest until now, but I definitely can't find a way to craft the Jade Longbow, do you think you can help me ? I can give you any informations you need if it helps !

![image](https://user-images.githubusercontent.com/69765221/133894200-232e674f-eeda-40a9-843d-e9003e675644.png)

I'm playing on a server I manage, with this configuration : 

forge1.12.2-14.23.5.2855
adventurepack-1.6.2
AmbientSounds_v3.0.9_mc1.12.2
Apotheosis-1.12.2-1.12.5
Baubles-1.12-1.5.2
BetterFps-1.4.8
bibliotheca-1.3.6-1.12.2
Bountiful-2.2.2
Chameleon-1.12-4.1.3
Chisel-MC1.12.2-1.0.2.45
ClassicCombat-1.12-1.0.0
CreativeCore_v1.10.62_mc1.12.2
CTM-MC1.12.2-1.0.2.31
DynamicTrees-1.12.2-0.9.25
Explorercraft-2.2.13
Floating-Rails-2.0.2-1.12.2
Forgelin-1.8.3
jei_1.12.2-4.15.0.283
journeymap-1.12.2-5.7.1
Neat+1.4-17
OptiFine_1.12.2_HD_U_F5
Placebo-1.12.2-1.6.0
ProgressiveBosses-1.5.2-mc1.12.x
StorageDrawers-1.12.2-5.4.2
Thaumcraft-1.12.2-6.1.BETA26
ToolBelt-1.12.2-1.9.9
twilightforest-1.12.2-3.11.1021-universal
u_team_core-1.12.2-2.2.5.147
useful_backpacks-1.12.2-1.5.4.85
VanillaTweaks-1.12.2-1.5.6

**Comment by FLoCkeYE** [comment]
Hi again, I just tried to update the mod to version 2.2.14 but I still have the problem, I also tried crafting it with a "normal" crafting table instead of the crafting pad, but it still the same, I really hope you can help me !

**Comment by Zathrox** [comment]
This is for the 1.12 version of the game, correct? That looks like the correct crafting recipe, I can take a general look but if its 1.12, unfortunately I can't update and fix the mod anymore for that version. That version is so old, I can't even remember if they had the crafting recipes in datapacks yet, if they do, you could make a small datapack to fix it if they do.

**Comment by Zathrox** [comment]
Closing this as I no longer support 1.12 version of the game. Will be updating to 1.20 soon! Keep an eye out
