### ISSUE TITLE
Flashing villager trade screen

### ISSUE THREAD

**Issue by Lunar-Rose** [Zathrox/Explorercraft#6]
Hey, I am reporting this to you because it happened when I viewed a Leek (from your mod) in a villager trade screen, what happened is it froze up for a second, then started rapidly flashing the trade window open/closed, enough that had I been epileptic I would be seizing up right now. I have a recording of said event because I was recording for a youtube video I am going to put out and I have the log for it because after the flashing was done it CTD'ed, so here is the log https://pastebin.com/uVaSsnhD and let me know if you want the video I will cut it out and PM it to you with a private link so that way we don't accidentally hurt people. -note also left a message on your mods curseforge comments about this

**Comment by Lunar-Rose** [comment]
also if I dont hear back within 2 days I will join your discord to message you about it

**Comment by Zathrox** [comment]
hello lunar, as mentioned on the curseforge page, I've checked the log and I can't see anything in that log that links to my mod but there are loads of random errors and i don't think its my mod causing it, unless you're playing with just my mod installed?

**Comment by Lunar-Rose** [comment]
I can make a load order with just that mod and test if it does it

**Comment by Zathrox** [comment]
please do, as I said i've not noticed the issue, one thing that could be causing it, is what forge are you using? maybe a newer or older forge is possibly causing the issue if they changed something
