### ISSUE TITLE
Disable, Blacklist, or Modify?

### ISSUE THREAD

**Issue by Yourname942** [Zathrox/Explorercraft#8]
1) Is it possible to either disable/blacklist food from this mod, or modify the amount of hunger the food replenishes? I am using Pam's Harvestcraft and the foods from this mod are not balanced for it. 

2) Also, can you make it so we can blacklist certain items we don't want to include? Thank you.

**Comment by Zathrox** [comment]
Hey, what version of minecraft are you using? I could or do sort of have plans to do something similar to this, if it is easy enough.

**Comment by Zathrox** [comment]
If it is easy and possible, when I rewrite my mod for 1.16 which is coming out in a few days, i'll possible do this and implement it into the config files!
